trigger:
- master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Windows
        pool:
          vmImage: 'windows-2019'
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: '-c Debug'
            projects: 'Qit'
            requestedMajorVersion: 3
          displayName: 'dotnet build Debug'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: 'Qit.Tests'
            arguments: '-c Debug'
          displayName: 'dotnet test Debug'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: '-c Release'
            projects: 'Qit'
            requestedMajorVersion: 3
          displayName: 'dotnet build Release'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: 'Qit.Tests'
            arguments: '-c Release'
          displayName: 'dotnet test Release'
