trigger:
- master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Linux
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: '-c Release'
            projects: 'Qit'
            requestedMajorVersion: 3
          displayName: 'dotnet build Release'
        # Package a project
        - task: DotNetCoreCLI@2
          inputs:
            command: 'pack'
            configuration: 'Release'
            packagesToPack: 'Qit'
